version: 2

build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.11'
  commands:
    - pip install uv
    - uv venv
    - uv pip install '.[doc]'
    - uv run --no-sync sphinx-build -b dirhtml doc $READTHEDOCS_OUTPUT/html
    - uv run --no-sync sphinx-build -b epub doc $READTHEDOCS_OUTPUT/epub
    - find $READTHEDOCS_OUTPUT/epub -mindepth 1 ! -name '*.epub' -exec rm -rf {} +
    - uv run --no-sync sphinx-build -b latex doc $READTHEDOCS_OUTPUT/pdf
    - make -C $READTHEDOCS_OUTPUT/pdf
    - find $READTHEDOCS_OUTPUT/pdf -mindepth 1 ! -name '*.pdf' -exec rm -rf {} +