version: '3'

vars:
  # If you run bare environment or activated venv, set '' (blank string)
  RUN_PYTHON: 'uv run'

tasks:
  setup-dev:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen --all-extras'
      - '{{.RUN_PYTHON}} playwright install chromium'
      - 'lefthook install'
      - 'uv run tools/fetch_revealjs.py'
      - task: 'docs:apidoc'
  verify:
    desc: 'Verify environment by all procs'
    cmds:
      - 'lefthook run pre-commit --all-files'
      - '{{.RUN_PYTHON}} pytest'
      # NOTE: To decide about management translations
      # - task: 'docs:intl'
      - task: 'docs:apidoc'
      - task: 'docs:build-linkcheck'
      - task: 'docs:build-dirhtml'
      - task: 'demo:intl'
      - task: 'docs:build-linkcheck'
      - task: 'demo:build'
      - 'uv build'
  release-*:
    desc: 'Run release process'
    vars:
      VERSION: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.VERSION}}'
      - 'uv sync --all-extras --all-groups'  # To write out as lock-file
  release:
    desc: 'Run release process'
    cmds:
      - 'age update {{.CLI_ARGS}}'
      - 'uv sync --all-extras --all-groups'  # To write out as lock-file

includes:
  docs: './doc'
  demo: './demo'
